# Generated by Django 4.2.7 on 2023-11-06 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Press',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_id', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
